Repository cloud-native-toolkit/image-cli-tools-ibmcloud, pull requests merged in 2022-08, with the labels that each got.

#9 Fix permissions for IBM cloud cli plugin directory
  Dockerfile
Labels: bug, patch

#11 Updates base image to v1.4.0
  .github/workflows/docker-build.yaml
  Containerfile
Labels: feature, minor

#12 Updates base to v1.4.1
  Containerfile
Labels: bug, patch

#13 Adds workflow to automatically update base image version
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#14 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.2
  Containerfile
Labels: bug, patch

#15 Adds job to notify downstream repositories
  .github/workflows/docker-build.yaml
Labels: chore, patch

#16 Updates README
  README.md
Labels: chore, patch

#17 Updates readme
  README.md
Labels: chore, patch

#18 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  Containerfile
Labels: bug, patch

#19 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  Containerfile
Labels: bug, patch

#20 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  Containerfile
Labels: bug, patch

#21 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  Containerfile
Labels: bug, patch
