Repository cloud-native-toolkit/image-cli-tools-ibmcloud, pull requests merged in 2025-03, with the labels that each got.

#40 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.0
  Containerfile
Labels: feature, minor

#41 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.1
  Containerfile
Labels: bug, patch

#42 Updates cloud-native-toolkit/image-cli-tools-core module to v2.0.2
  Containerfile
Labels: bug, patch

#43 Update logic to install ibm cloud cli and workflow build logic
  .github/workflows/docker-build.yaml
  Containerfile
Labels: chore, patch
